Update actionlinttest.yaml

diff --git a/.github/workflows/actionlinttest.yaml b/.github/workflows/actionlinttest.yaml
--- a/.github/workflows/actionlinttest.yaml
+++ b/.github/workflows/actionlinttest.yaml
@@ -38,9 +38,12 @@ jobs:
       shell: bash
       run: |
         actionlint
-        if [ $? -eq 1 ]; then
+        exit_code=$?  # Store the exit code immediately after running actionlint
+        
+        if [ $exit_code -eq 1 ]; then
             echo "Ignoring actionlint error"
         fi
+
 
 
         
